name: healpath
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  get:
  fl_chart: ^0.69.0
  url_launcher: ^6.3.0
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  pdf: ^3.8.4
  printing: ^5.9.3
  path_provider: ^2.0.15
  share_plus: ^10.0.2
  screenshot: ^3.0.0
  flutter_otp_text_field: ^1.2.0
  firebase_core: ^3.5.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

 
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
     

 